export const RAITU_NESTHAM_CHANNEL = {
  name: "Raitu Nestham",
  handle: "@Raitunestham",
  channelId: "UC7hcNyhpRKiO4oUg6iBkL2Q",
  url: "https://www.youtube.com/@Raitunestham",
  reviewedAt: "2026-08-25",
} as const;

export const RAITU_NESTHAM_PRIORITIES = ["recent", "method", "allied"] as const;

export type RaituNesthamPriority =
  (typeof RAITU_NESTHAM_PRIORITIES)[number];

export type RaituNesthamResearchRecord = {
  id: string;
  priority: RaituNesthamPriority;
  videoDate: string;
  farmerOrGroup: string;
  location: string;
  state: string | null;
  scale: string | null;
  farmingFocus: string;
  methodsOrCrops: string;
  channelReportedClaim: string | null;
  publicUnverifiedPhone: string | null;
  youtubeSource: `https://www.youtube.com/watch?v=${string}`;
};

export const RAITU_NESTHAM_RESEARCH = [
  {
    id: "k-bal-reddy-super-garden",
    priority: "recent",
    videoDate: "2026-08-24 approx.",
    farmerOrGroup: "K. Bal Reddy",
    location: "Bommayipalli, Yadadri Bhuvanagiri",
    state: "Telangana",
    scale: "400 square yards",
    farmingFocus: "Urban food garden",
    methodsOrCrops: "Fruit garden among coconut trees",
    channelReportedClaim: null,
    publicUnverifiedPhone: null,
    youtubeSource: "https://www.youtube.com/watch?v=TEd9HTGNZv4",
  },
  {
    id: "ramadevi-food-forest",
    priority: "recent",
    videoDate: "2026-08-18",
    farmerOrGroup: "Ramadevi and spouse",
    location: "Kodada, Suryapet",
    state: "Telangana",
    scale: "500 square yards",
    farmingFocus: "Food forest",
    methodsOrCrops: "Mixed fruits and vegetables",
    channelReportedClaim: "Presented as a productive family food forest.",
    publicUnverifiedPhone: null,
    youtubeSource: "https://www.youtube.com/watch?v=hlKlWcQYCf8",
  },
  {
    id: "komatla-nancha-reddy-groundnut",
    priority: "recent",
    videoDate: "2026-08-04",
    farmerOrGroup: "Komatla Nancha Reddy",
    location: "Motumula, Kothapatnam, Prakasam",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Natural groundnut",
    methodsOrCrops: "Groundnut; sprinkler irrigation",
    channelReportedClaim: "Title claims nearly ₹1 lakh return in three months.",
    publicUnverifiedPhone: "9849852470",
    youtubeSource: "https://www.youtube.com/watch?v=fdNm7SAbFaA",
  },
  {
    id: "m-ramakrishna-okra",
    priority: "recent",
    videoDate: "2026-07-14",
    farmerOrGroup: "M. Ramakrishna",
    location: "Nandivelugu, Guntur",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Organic and natural okra",
    methodsOrCrops: "Tender okra production and marketing",
    channelReportedClaim: "Description says tender organic okra can attract higher prices.",
    publicUnverifiedPhone: "9989646499",
    youtubeSource: "https://www.youtube.com/watch?v=L1Gq1hJpkLo",
  },
  {
    id: "kolluri-srinivasa-rao-leafy-greens",
    priority: "recent",
    videoDate: "2026-07-09",
    farmerOrGroup: "Kolluri Srinivasa Rao",
    location: "Madanur, Kothapatnam, Prakasam",
    state: "Andhra Pradesh",
    scale: "1.5 acres",
    farmingFocus: "Organic leafy vegetables",
    methodsOrCrops: "Ten leafy-green varieties; direct marketing",
    channelReportedClaim: "Description claims ₹5 bunches and about ₹60,000 monthly income.",
    publicUnverifiedPhone: "9553733113",
    youtubeSource: "https://www.youtube.com/watch?v=IA9dS3qMyAk",
  },
  {
    id: "venkatrao-natural-multicrop",
    priority: "recent",
    videoDate: "2026-05-02",
    farmerOrGroup: "Venkatrao",
    location: "Neeladripuram, Unguturu, Eluru",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Natural multi-crop farming",
    methodsOrCrops: "Multiple crops; own and direct market",
    channelReportedClaim: "Channel reports good direct-market results.",
    publicUnverifiedPhone: "9490391371",
    youtubeSource: "https://www.youtube.com/watch?v=aSbxYiEkgF4",
  },
  {
    id: "kondareddy-natural-farming",
    priority: "recent",
    videoDate: "2026-04-13",
    farmerOrGroup: "Kondareddy",
    location: "Miras Palli, Kothakota, Wanaparthy",
    state: "Telangana",
    scale: "50 acres",
    farmingFocus: "Natural farming",
    methodsOrCrops: "Natural plant extracts; jeevamrutham; duration-diverse crops",
    channelReportedClaim: "Channel reports good yields.",
    publicUnverifiedPhone: null,
    youtubeSource: "https://www.youtube.com/watch?v=GlIBxAWxSSg",
  },
  {
    id: "chinna-venkateswarlu-red-gram",
    priority: "recent",
    videoDate: "2026-04-11",
    farmerOrGroup: "Chinna Venkateswarlu",
    location: "Petasannigandla, Karampudi, Palnadu",
    state: "Andhra Pradesh",
    scale: "34 acres",
    farmingFocus: "Natural red gram",
    methodsOrCrops: "Primarily red gram",
    channelReportedClaim: "Title reports strong earnings without an audited amount.",
    publicUnverifiedPhone: "9000943974",
    youtubeSource: "https://www.youtube.com/watch?v=WvpU4x4oJ1c",
  },
  {
    id: "chilukuri-vishweshwara-rao-integrated",
    priority: "recent",
    videoDate: "2026-04-06",
    farmerOrGroup: "Chilukuri Vishweshwara Rao",
    location: "Achanta, West Godavari",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Integrated natural farming",
    methodsOrCrops: "Dairy and crops; cow-linked farming",
    channelReportedClaim: null,
    publicUnverifiedPhone: "8985606938",
    youtubeSource: "https://www.youtube.com/watch?v=LlbTGBa9qnI",
  },
  {
    id: "uday-krishna-reddy-horticulture",
    priority: "recent",
    videoDate: "2026-02-19",
    farmerOrGroup: "Uday Krishna Reddy",
    location: "Akkulagaripalli, Lingala, Kadapa",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Organic horticulture",
    methodsOrCrops: "Tomato; sweet lime and citrus; intercrops",
    channelReportedClaim: "Companion title states a 1,600-box tomato target, not achieved output.",
    publicUnverifiedPhone: "9100419163",
    youtubeSource: "https://www.youtube.com/watch?v=lDIeBLEcDmg",
  },
  {
    id: "kambhampati-satyanarayana-jaggery",
    priority: "recent",
    videoDate: "2026-02-10",
    farmerOrGroup: "Kambhampati Satyanarayana",
    location: "Pallerlamudi, Nuzvid, Eluru",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Organic sugarcane and value addition",
    methodsOrCrops: "Sugarcane; natural jaggery",
    channelReportedClaim: "Channel claims product reaches the USA; not independently verified.",
    publicUnverifiedPhone: "6302529160",
    youtubeSource: "https://www.youtube.com/watch?v=uIEnc1yXKTU",
  },
  {
    id: "bala-maddileti-native-paddy",
    priority: "recent",
    videoDate: "2025-11-06",
    farmerOrGroup: "Kharreddula Bala Maddileti",
    location: "Jillella, Gospadu, Nandyal",
    state: "Andhra Pradesh",
    scale: "6 acres",
    farmingFocus: "Natural and native paddy",
    methodsOrCrops: "Native paddy; no chemical fertilizer; natural-produce market",
    channelReportedClaim: "Channel reports good yields.",
    publicUnverifiedPhone: "8465953244",
    youtubeSource: "https://www.youtube.com/watch?v=By4Sn7vURMA",
  },
  {
    id: "adapa-lakshmi-coffee",
    priority: "recent",
    videoDate: "2025-11-01",
    farmerOrGroup: "Adapa Lakshmi",
    location: "Nittamamidi Palem, G.K. Veedhi, Alluri Sitarama Raju",
    state: "Andhra Pradesh",
    scale: "10 acres",
    farmingFocus: "Natural and organic coffee",
    methodsOrCrops: "Coffee and mixed crops in hill terrain",
    channelReportedClaim: "Channel presents a successful coffee farm without figures.",
    publicUnverifiedPhone: "8885392074",
    youtubeSource: "https://www.youtube.com/watch?v=bEsPRFMdbmk",
  },
  {
    id: "krishna-mohan-reddy-banana",
    priority: "recent",
    videoDate: "2025-10-25",
    farmerOrGroup: "Krishna Mohan Reddy",
    location: "Garladinne, Peddapappur, Anantapur",
    state: "Andhra Pradesh",
    scale: "26 acres",
    farmingFocus: "Natural banana and mixed farming",
    methodsOrCrops: "Mainly banana; mixed crops",
    channelReportedClaim: "Title claims ₹1 lakh profit per acre.",
    publicUnverifiedPhone: "6302830162",
    youtubeSource: "https://www.youtube.com/watch?v=vWh1PR-78Jk",
  },
  {
    id: "jyoti-natural-paddy",
    priority: "recent",
    videoDate: "2025-10-21",
    farmerOrGroup: "Jyoti",
    location: "Fattepur, Chilpur, Jangaon",
    state: "Telangana",
    scale: "10 acres",
    farmingFocus: "Natural paddy",
    methodsOrCrops: "Paddy using fully natural methods",
    channelReportedClaim: "Title claims 450 bags; description says good yield.",
    publicUnverifiedPhone: "8008837512",
    youtubeSource: "https://www.youtube.com/watch?v=nDvtjd-iOIo",
  },
  {
    id: "gopala-krishna-paddy-vegetables",
    priority: "recent",
    videoDate: "2025-10-18",
    farmerOrGroup: "Gopala Krishna",
    location: "Endapalli, Chintalapudi, Eluru",
    state: "Andhra Pradesh",
    scale: "Expanded from 0.5 to 2.5 acres",
    farmingFocus: "Palekar-inspired natural farming",
    methodsOrCrops: "Native paddy; vegetables on bunds",
    channelReportedClaim: "Channel reports good yields.",
    publicUnverifiedPhone: "9963559936",
    youtubeSource: "https://www.youtube.com/watch?v=xT2UNY703Yw",
  },
  {
    id: "dhananjay-rao-two-season",
    priority: "recent",
    videoDate: "2025-10-08",
    farmerOrGroup: "Dhananjay Rao",
    location: "Vatticherukuru, Guntur",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Two-season natural farming",
    methodsOrCrops: "Paddy and pulses; low-input approach",
    channelReportedClaim: null,
    publicUnverifiedPhone: "9494390655",
    youtubeSource: "https://www.youtube.com/watch?v=r82S2zZFYo8",
  },
  {
    id: "nukaratnam-sugarcane-jaggery",
    priority: "recent",
    videoDate: "2025-09-26",
    farmerOrGroup: "Nukaratnam",
    location: "Ganaparthi, Munagapaka, Anakapalli",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Natural and organic sugarcane",
    methodsOrCrops: "Sugarcane; jaggery; own marketing",
    channelReportedClaim: "Title claims ₹2 lakh income.",
    publicUnverifiedPhone: "7330824407",
    youtubeSource: "https://www.youtube.com/watch?v=3EdCfIbenXA",
  },
  {
    id: "rangarao-native-paddy",
    priority: "recent",
    videoDate: "2025-09-08",
    farmerOrGroup: "Rangarao",
    location: "Kondapavuluru, Gannavaram, Krishna",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Natural native paddy",
    methodsOrCrops: "Desi paddy",
    channelReportedClaim: null,
    publicUnverifiedPhone: "9985692555",
    youtubeSource: "https://www.youtube.com/watch?v=UssRGGddsMk",
  },
  {
    id: "naveen-palekar-mixed",
    priority: "recent",
    videoDate: "2025-08-28",
    farmerOrGroup: "Naveen",
    location: "Narsingapuram, Pithapuram area, Kakinada",
    state: "Andhra Pradesh",
    scale: "4 acres",
    farmingFocus: "Palekar mixed farming",
    methodsOrCrops: "Coconut; turmeric; paddy; banana; custard apple",
    channelReportedClaim: null,
    publicUnverifiedPhone: null,
    youtubeSource: "https://www.youtube.com/watch?v=G7nsN7qX_hE",
  },
  {
    id: "shyam-organic-rotation",
    priority: "recent",
    videoDate: "2025-06-06",
    farmerOrGroup: "Shyam",
    location: "Pudi, Thottambedu, Tirupati",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Organic crop rotation",
    methodsOrCrops: "No-chemical crop rotation",
    channelReportedClaim: "Channel presents improved satisfaction after leaving IT.",
    publicUnverifiedPhone: "9618674906",
    youtubeSource: "https://www.youtube.com/watch?v=ALoQEW4bXHI",
  },
  {
    id: "chandul-kumar-reddy-heritage-rice",
    priority: "recent",
    videoDate: "2025-06-03",
    farmerOrGroup: "Chandul Kumar Reddy",
    location: "Kurmai, Palamaner, Chittoor",
    state: "Andhra Pradesh",
    scale: "4 acres",
    farmingFocus: "Heritage rice conservation",
    methodsOrCrops: "Eleven desi rice seed varieties; natural farming",
    channelReportedClaim: null,
    publicUnverifiedPhone: "6300027502",
    youtubeSource: "https://www.youtube.com/watch?v=WkXsWG9lJps",
  },
  {
    id: "srinivas-reddy-organic-banana",
    priority: "recent",
    videoDate: "2025-05-31",
    farmerOrGroup: "Srinivas Reddy",
    location: "Kothapalem, Mangalagiri, Guntur",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Organic and natural horticulture",
    methodsOrCrops: "Banana; turmeric; tuber crops; no chemicals",
    channelReportedClaim: null,
    publicUnverifiedPhone: "9866339832",
    youtubeSource: "https://www.youtube.com/watch?v=XkjcCzhbPCM",
  },
  {
    id: "vijayalakshmi-diverse-natural",
    priority: "recent",
    videoDate: "2025-05-06",
    farmerOrGroup: "Vijayalakshmi",
    location: "Erukalapudi, Tenali, Guntur",
    state: "Andhra Pradesh",
    scale: "3 acres",
    farmingFocus: "Diverse natural farming",
    methodsOrCrops: "Multiple crops",
    channelReportedClaim: "Channel presents an income-diversification model.",
    publicUnverifiedPhone: "9177157036",
    youtubeSource: "https://www.youtube.com/watch?v=zAh-pAveLG0",
  },
  {
    id: "sriramulu-zero-budget-orchard",
    priority: "recent",
    videoDate: "2025-04-15",
    farmerOrGroup: "Sriramulu",
    location: "Gudur, Kurnool",
    state: "Andhra Pradesh",
    scale: "150 acres",
    farmingFocus: "Zero-budget orchard",
    methodsOrCrops: "Mango and diverse fruit crops; 25-year practice",
    channelReportedClaim: null,
    publicUnverifiedPhone: "9441096868",
    youtubeSource: "https://www.youtube.com/watch?v=8EC9HFT2l7I",
  },
  {
    id: "rosaiah-five-layer",
    priority: "method",
    videoDate: "2018-07-20",
    farmerOrGroup: "Rosaiah",
    location: "Athotu, Guntur",
    state: "Andhra Pradesh",
    scale: "75 cents",
    farmingFocus: "Five-layer natural farming",
    methodsOrCrops: "24 crop types; waaphasa; jeevamrutham; ghanajeevamrutham; beejamrutham; NADEP compost",
    channelReportedClaim: "Channel claims coconut alone exceeds ₹1 lakh per year.",
    publicUnverifiedPhone: "9666532921",
    youtubeSource: "https://www.youtube.com/watch?v=xV4xXyaI2wU",
  },
  {
    id: "mallareddy-zbnf-lemon",
    priority: "method",
    videoDate: "2018-07-11",
    farmerOrGroup: "Mallareddy",
    location: "Munnangivaripalem, Chunduru, Guntur",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Zero-budget lemon orchard",
    methodsOrCrops: "Jeevamrutham; neemasthram; agniasthram; sour buttermilk; leaf mulch",
    channelReportedClaim: "Channel claims about ₹1 lakh net per acre per year.",
    publicUnverifiedPhone: "7799273612",
    youtubeSource: "https://www.youtube.com/watch?v=EHfr8kctjMI",
  },
  {
    id: "bandaru-venkateshwarlu-organic-mixed",
    priority: "method",
    videoDate: "2018-09-01",
    farmerOrGroup: "Bandaru Venkateshwarlu",
    location: "Narsimhulagudem, Munagala, Suryapet",
    state: "Telangana",
    scale: "11 acres",
    farmingFocus: "Organic mixed farming",
    methodsOrCrops: "Vegetables; fruit; paddy; trap crops; light traps; pond; drip; neem extract",
    channelReportedClaim: null,
    publicUnverifiedPhone: "7702710588",
    youtubeSource: "https://www.youtube.com/watch?v=JstyCRAuC9U",
  },
  {
    id: "boddu-narsimhulu-organic-vegetables",
    priority: "method",
    videoDate: "2021-12-04",
    farmerOrGroup: "Boddu Narsimhulu and son",
    location: "Ksheerasagar, Mulugu, Siddipet",
    state: "Telangana",
    scale: "1 acre",
    farmingFocus: "Organic vegetables",
    methodsOrCrops: "25 vegetable varieties; cow waste; FPC marketing",
    channelReportedClaim: "Title claims two harvests per week and ₹9,000 per harvest.",
    publicUnverifiedPhone: "9705313239",
    youtubeSource: "https://www.youtube.com/watch?v=6y3IFos9k_4",
  },
  {
    id: "alwala-balayya-shetty-palekar",
    priority: "method",
    videoDate: "2022-02-02",
    farmerOrGroup: "Alwala Balayya Shetty",
    location: "Nandikotkur, Kurnool",
    state: "Andhra Pradesh",
    scale: "40 acres",
    farmingFocus: "Palekar natural farming",
    methodsOrCrops: "Papaya; groundnut; sugarcane; black gram; banana; natural inputs",
    channelReportedClaim: "Channel reports low cost and good profits without figures.",
    publicUnverifiedPhone: "9490482857",
    youtubeSource: "https://www.youtube.com/watch?v=5ZEElKT2dmQ",
  },
  {
    id: "malyadri-five-layer-food-forest",
    priority: "method",
    videoDate: "2025-03-31",
    farmerOrGroup: "Malyadri",
    location: "Near Buchireddypalem, Nellore",
    state: "Andhra Pradesh",
    scale: "3 acres",
    farmingFocus: "Five-layer food forest",
    methodsOrCrops: "Food-forest model under development",
    channelReportedClaim: null,
    publicUnverifiedPhone: "8886401248",
    youtubeSource: "https://www.youtube.com/watch?v=-kZ-9PHK3YU",
  },
  {
    id: "munipalle-harinath-food-forest",
    priority: "method",
    videoDate: "2022-12-03",
    farmerOrGroup: "Munipalle Harinath",
    location: "Munipalle, Ponnur, Guntur",
    state: "Andhra Pradesh",
    scale: "0.5-acre food forest; total not stated",
    farmingFocus: "Natural mixed farming",
    methodsOrCrops: "Paddy; grains; fruit; vegetables; natural mixtures; value addition; own marketing",
    channelReportedClaim: "Channel reports low investment and labour-aligned return.",
    publicUnverifiedPhone: "9380516443",
    youtubeSource: "https://www.youtube.com/watch?v=mgqwWoG2QMk",
  },
  {
    id: "nandyala-edukondalu-food-forest",
    priority: "method",
    videoDate: "2022-10-12",
    farmerOrGroup: "Nandyala Edukondalu",
    location: "Piduguralla, Guntur",
    state: "Andhra Pradesh",
    scale: "4 acres plus 0.5-acre food forest",
    farmingFocus: "Natural mixed farming",
    methodsOrCrops: "Paddy; vegetables; fruit; family food forest",
    channelReportedClaim: "Channel presents continuous and long-term income potential.",
    publicUnverifiedPhone: "9704821223",
    youtubeSource: "https://www.youtube.com/watch?v=4L-kOiKAhuw",
  },
  {
    id: "parvataneni-venkata-srinivas-orchard",
    priority: "method",
    videoDate: "2021-06-04",
    farmerOrGroup: "Parvataneni Venkata Srinivas",
    location: "Edupugallu, Kankipadu, Krishna",
    state: "Andhra Pradesh",
    scale: "4 acres",
    farmingFocus: "Natural and organic orchard",
    methodsOrCrops: "40 fruit-tree types; farm-gate direct sales",
    channelReportedClaim: "Channel reports regular daily income.",
    publicUnverifiedPhone: "9392922007",
    youtubeSource: "https://www.youtube.com/watch?v=DWrsy6T4e6Q",
  },
  {
    id: "gopala-krishna-murthy-green-manure",
    priority: "method",
    videoDate: "2021-10-26",
    farmerOrGroup: "Gopala Krishna Murthy",
    location: "Gundugolanugunta, Dwaraka Tirumala, West Godavari",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Natural soil-building",
    methodsOrCrops: "Oil palm; lemon; paddy; nine-seed green manure",
    channelReportedClaim: "Channel claims improved soil, crop quality and returns.",
    publicUnverifiedPhone: "9491179182",
    youtubeSource: "https://www.youtube.com/watch?v=FuUAQUP_Zug",
  },
  {
    id: "sreenu-zbnf-mixed",
    priority: "method",
    videoDate: "2024-10-10",
    farmerOrGroup: "Sreenu",
    location: "Chinnatandrapadu, Aiza, Jogulamba Gadwal",
    state: "Telangana",
    scale: null,
    farmingFocus: "Zero-budget natural farming",
    methodsOrCrops: "Paddy; red gram; chilli; intercrops",
    channelReportedClaim: "Channel reports good and increasing yields.",
    publicUnverifiedPhone: "8074661926",
    youtubeSource: "https://www.youtube.com/watch?v=wXIZzxJhVvs",
  },
  {
    id: "satyanarayana-natural-oil-palm",
    priority: "method",
    videoDate: "2020-08-03",
    farmerOrGroup: "Satyanarayana",
    location: "M. Nagulapalli, Dwaraka Tirumala, West Godavari",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Natural oil palm",
    methodsOrCrops: "Weeds retained as mulch instead of chemical herbicide",
    channelReportedClaim: "Channel claims lower costs and better bunch quality.",
    publicUnverifiedPhone: "9490110409",
    youtubeSource: "https://www.youtube.com/watch?v=c6ZOv6r3sOU",
  },
  {
    id: "prasad-reddy-integrated-food-forest",
    priority: "method",
    videoDate: "2024-07-17",
    farmerOrGroup: "Prasad Reddy",
    location: "Shamirpet, Medchal",
    state: "Telangana",
    scale: null,
    farmingFocus: "Integrated natural food forest",
    methodsOrCrops: "100+ stated fruit varieties; medicinal plants; vegetables; pulses",
    channelReportedClaim: null,
    publicUnverifiedPhone: "6302049504",
    youtubeSource: "https://www.youtube.com/watch?v=Rg5I-6rP9I4",
  },
  {
    id: "narsanna-padmavati-permaculture",
    priority: "method",
    videoDate: "2021-10-23",
    farmerOrGroup: "Narsanna and Padmavati",
    location: "Not stated in accessible description",
    state: null,
    scale: null,
    farmingFocus: "Permaculture",
    methodsOrCrops: "25-year forest with fruit and large trees, medicinal plants and food crops",
    channelReportedClaim: "Channel presents a low-input permaculture model.",
    publicUnverifiedPhone: "9440826722",
    youtubeSource: "https://www.youtube.com/watch?v=INOg9H6xXsA",
  },
  {
    id: "gadde-venkataratnam-paddy-fish",
    priority: "recent",
    videoDate: "2026-07 approx.",
    farmerOrGroup: "Gadde Venkataratnam",
    location: "Unguturu, Eluru",
    state: "Andhra Pradesh",
    scale: null,
    farmingFocus: "Integrated natural farming",
    methodsOrCrops: "Paddy and fish; own and direct marketing",
    channelReportedClaim: "Channel reports good profits.",
    publicUnverifiedPhone: "9121147782",
    youtubeSource: "https://www.youtube.com/watch?v=3O_513wqs_E",
  },
  {
    id: "jyothi-milky-mushrooms",
    priority: "allied",
    videoDate: "2026-07-25",
    farmerOrGroup: "Jyothi",
    location: "Not established in accessible description",
    state: null,
    scale: null,
    farmingFocus: "Mushroom enterprise and training",
    methodsOrCrops: "Milky mushrooms; unit operation; marketing",
    channelReportedClaim: "Description says a low-investment unit can create income.",
    publicUnverifiedPhone: "9985511793",
    youtubeSource: "https://www.youtube.com/watch?v=gqsBvJVFujE",
  },
] as const satisfies readonly RaituNesthamResearchRecord[];

function normalizeSearchValue(value: string) {
  return value.normalize("NFKC").trim().toLocaleLowerCase("en-IN");
}

export function filterRaituNesthamResearch(input: {
  q?: string;
  priority?: RaituNesthamPriority;
}) {
  const query = normalizeSearchValue(input.q ?? "").slice(0, 120);
  return RAITU_NESTHAM_RESEARCH.filter((record) => {
    if (input.priority && record.priority !== input.priority) return false;
    if (!query) return true;
    return [
      record.farmerOrGroup,
      record.location,
      record.state,
      record.scale,
      record.farmingFocus,
      record.methodsOrCrops,
      record.channelReportedClaim,
      record.publicUnverifiedPhone,
    ].some((value) => normalizeSearchValue(value ?? "").includes(query));
  });
}

export function summarizeRaituNesthamResearch(
  records: readonly RaituNesthamResearchRecord[] = RAITU_NESTHAM_RESEARCH,
) {
  return {
    total: records.length,
    withPublicPhone: records.filter((record) => record.publicUnverifiedPhone).length,
    recent: records.filter((record) => record.priority === "recent").length,
    method: records.filter((record) => record.priority === "method").length,
    allied: records.filter((record) => record.priority === "allied").length,
  };
}
