import type {
  Comment,
  Conversation,
  FarmerPost,
  FarmerProfile,
  Message,
  ModerationReport,
} from "@/lib/types";

export const currentUserId = "meera";

export const profiles: FarmerProfile[] = [
  {
    id: "meera",
    handle: "meera_kulkarni",
    fullName: "Meera Kulkarni",
    initials: "MK",
    participantType: "farmer",
    accountRole: "farmer",
    roleLabel: "Farmer",
    preferredLocale: "en-IN",
    categoryAffinities: [],
    district: "Nashik",
    state: "Maharashtra",
    crops: ["Tomato", "Onion", "Okra"],
    bio: "Second-generation farmer learning protected cultivation and sharing practical notes from our family farm.",
    farmingMethod: "natural",
    socialLinks: {
      instagram: "https://www.instagram.com/farmerbook",
      youtube: "https://www.youtube.com/@farmerbook",
    },
    reviewSummary: { average: 4.8, count: 12 },
    verified: true,
    followers: 128,
    following: 74,
    experienceYears: 8,
    joinedLabel: "Joined July 2026",
    publicProfileEnabled: true,
  },
  {
    id: "ramesh",
    handle: "ramesh_patil",
    fullName: "Ramesh Patil",
    initials: "RP",
    participantType: "farmer",
    accountRole: "farmer",
    roleLabel: "Farmer",
    preferredLocale: "en-IN",
    categoryAffinities: [],
    district: "Nashik",
    state: "Maharashtra",
    crops: ["Tomato", "Chilli"],
    bio: "Growing open-field and protected tomatoes. Interested in disease prevention and low-cost irrigation.",
    farmingMethod: "organic",
    organicCertificationVerified: false,
    socialLinks: {},
    reviewSummary: { average: 4.6, count: 8 },
    verified: true,
    followers: 214,
    following: 86,
    experienceYears: 16,
    joinedLabel: "Joined July 2026",
    isFollowing: true,
    publicProfileEnabled: true,
  },
  {
    id: "anjali",
    handle: "anjali_agronomy",
    fullName: "Anjali Deshmukh",
    initials: "AD",
    participantType: "agronomist",
    accountRole: "customer",
    roleLabel: "Customer",
    preferredLocale: "en-IN",
    categoryAffinities: [],
    district: "Pune",
    state: "Maharashtra",
    crops: ["Tomato", "Grapes", "Pomegranate"],
    bio: "Field agronomist helping small farms improve water use and crop health through practical workshops.",
    socialLinks: {
      linkedin: "https://www.linkedin.com/company/farmerbook",
    },
    reviewSummary: { average: 0, count: 0 },
    verified: true,
    followers: 356,
    following: 121,
    experienceYears: 11,
    joinedLabel: "Joined July 2026",
    isFollowing: true,
    publicProfileEnabled: false,
  },
  {
    id: "suresh",
    handle: "suresh_grapes",
    fullName: "Suresh Kale",
    initials: "SK",
    participantType: "farmer",
    accountRole: "farmer",
    roleLabel: "Farmer",
    preferredLocale: "en-IN",
    categoryAffinities: [],
    district: "Nashik",
    state: "Maharashtra",
    crops: ["Grapes"],
    bio: "Table grape grower documenting canopy management, residue-safe practices and export preparation.",
    farmingMethod: "mixed",
    socialLinks: {},
    reviewSummary: { average: 4.9, count: 19 },
    verified: true,
    followers: 189,
    following: 63,
    experienceYears: 21,
    joinedLabel: "Joined July 2026",
    publicProfileEnabled: true,
  },
  {
    id: "priya",
    handle: "priya_soils",
    fullName: "Priya Nair",
    initials: "PN",
    participantType: "trainer",
    accountRole: "customer",
    roleLabel: "Customer",
    preferredLocale: "en-IN",
    categoryAffinities: [],
    district: "Pune",
    state: "Maharashtra",
    crops: ["Onion", "Tomato", "Millets"],
    bio: "Soil health trainer translating lab reports into simple field decisions.",
    socialLinks: {},
    reviewSummary: { average: 0, count: 0 },
    verified: true,
    followers: 291,
    following: 94,
    experienceYears: 13,
    joinedLabel: "Joined July 2026",
    publicProfileEnabled: false,
  },
  {
    id: "vikram",
    handle: "vikram_fpo",
    fullName: "Vikram Jadhav",
    initials: "VJ",
    participantType: "fpo",
    accountRole: "wholesaler",
    roleLabel: "Wholesaler",
    preferredLocale: "en-IN",
    categoryAffinities: [],
    district: "Ahmednagar",
    state: "Maharashtra",
    crops: ["Onion", "Pomegranate"],
    bio: "Working with farmer groups on aggregation, grading and reliable buyer relationships.",
    socialLinks: {
      website: "https://farmerbook.in",
      linkedin: "https://www.linkedin.com/company/farmerbook",
    },
    reviewSummary: { average: 4.7, count: 15 },
    verified: false,
    followers: 97,
    following: 118,
    experienceYears: 7,
    joinedLabel: "Joined July 2026",
    publicProfileEnabled: false,
  },
];

export const posts: FarmerPost[] = [
  {
    id: "tomato-leaf-spots",
    authorId: "ramesh",
    body: "White spots started appearing on the lower tomato leaves after last week’s rain. Has anyone nearby seen this pattern? I have paused the usual spray until I understand whether this is fungal or a nutrient issue.",
    category: "question",
    crops: ["Tomato"],
    createdLabel: "18 min ago",
    helpfulCount: 24,
    commentCount: 8,
    imageVariant: "tomato",
  },
  {
    id: "drip-workshop",
    authorId: "anjali",
    body: "Hosting a practical drip irrigation workshop this Saturday near Pune. We will cover pressure checks, simple filtration maintenance and scheduling by crop stage. I’ve added five seats for FarmerBook members.",
    category: "opportunity",
    crops: ["Water management"],
    createdLabel: "1 hr ago",
    helpfulCount: 41,
    commentCount: 12,
    helpfulByViewer: true,
    imageVariant: "irrigation",
  },
  {
    id: "grape-canopy",
    authorId: "suresh",
    body: "We finished the first round of canopy thinning today. Leaving a little more air around the bunches has reduced humidity after evening irrigation. Sharing our row spacing notes for anyone comparing methods.",
    category: "discussion",
    crops: ["Grapes"],
    createdLabel: "3 hr ago",
    helpfulCount: 32,
    commentCount: 6,
    imageVariant: "grapes",
  },
];

export const comments: Comment[] = [
  {
    id: "comment-1",
    postId: "tomato-leaf-spots",
    authorId: "priya",
    body: "Check whether the spots rub off and inspect the underside in the early morning. That will help separate residue from fungal growth.",
    createdLabel: "11 min ago",
  },
  {
    id: "comment-2",
    postId: "tomato-leaf-spots",
    authorId: "anjali",
    body: "Please share one close photo of the underside before spraying. Several farms saw powdery mildew after the same humid spell.",
    createdLabel: "7 min ago",
  },
  {
    id: "comment-3",
    postId: "tomato-leaf-spots",
    authorId: "meera",
    body: "I saw something similar on two rows. I’ll compare the underside this evening and update here.",
    createdLabel: "2 min ago",
  },
];

export const conversations: Conversation[] = [
  {
    id: "conversation-ramesh",
    otherProfileId: "ramesh",
    lastMessage: "I’ll send another leaf photo after sunset.",
    updatedLabel: "12 min",
    unread: 2,
  },
  {
    id: "conversation-anjali",
    otherProfileId: "anjali",
    lastMessage: "Yes, I have kept one workshop seat for you.",
    updatedLabel: "1 hr",
    unread: 0,
  },
  {
    id: "conversation-vikram",
    otherProfileId: "vikram",
    lastMessage: "The grading centre opens at 8:30 on Monday.",
    updatedLabel: "Yesterday",
    unread: 0,
  },
];

export const messages: Message[] = [
  {
    id: "message-1",
    conversationId: "conversation-ramesh",
    senderId: "meera",
    body: "Namaskar Ramesh. We had the same rain. Are the spots mostly on older leaves?",
    createdLabel: "10:18",
  },
  {
    id: "message-2",
    conversationId: "conversation-ramesh",
    senderId: "ramesh",
    body: "Yes, mainly the lower leaves. New growth still looks clean.",
    createdLabel: "10:23",
  },
  {
    id: "message-3",
    conversationId: "conversation-ramesh",
    senderId: "meera",
    body: "That helps. I’m checking the underside on my rows this evening.",
    createdLabel: "10:26",
  },
  {
    id: "message-4",
    conversationId: "conversation-ramesh",
    senderId: "ramesh",
    body: "I’ll send another leaf photo after sunset.",
    createdLabel: "10:31",
  },
];

export const reports: ModerationReport[] = [
  {
    id: "report-1",
    reporterId: "meera",
    targetType: "post",
    targetId: "tomato-leaf-spots",
    targetLabel: "Post claiming a guaranteed overnight crop cure",
    reason: "misinformation",
    details: "The post recommends an unlabeled chemical mixture and promises guaranteed results.",
    createdLabel: "24 min ago",
    status: "pending",
  },
  {
    id: "report-2",
    reporterId: "ramesh",
    targetType: "profile",
    targetId: "vikram",
    targetLabel: "Account repeatedly advertising unrelated loans",
    reason: "spam",
    details: "The account sent the same loan link in comments and private messages.",
    createdLabel: "2 hr ago",
    status: "pending",
  },
];

export function getProfile(id: string) {
  return profiles.find((profile) => profile.id === id) ?? profiles[0];
}

export function getPost(id: string) {
  return posts.find((post) => post.id === id) ?? posts[0];
}
