import { getProfile } from "@/lib/demo-data";
import type {
  MarketEnquiry,
  MarketReview,
  ProduceListing,
} from "@/lib/types";

export const produceListings: ProduceListing[] = [
  {
    id: "nashik-roma-tomatoes",
    sellerId: "meera",
    title: "Fresh Roma tomatoes — weekly harvest",
    crop: "Tomato",
    variety: "Roma VF",
    description:
      "Firm, evenly ripened tomatoes from our family farm. Hand-sorted on harvest morning and packed in ventilated crates for retailers, restaurants and community buying groups.",
    quantity: 32,
    unit: "quintal",
    minOrder: 50,
    price: 28,
    priceUnit: "kg",
    harvestStart: "3 Aug",
    harvestEnd: "28 Aug",
    availableUntil: "28 Aug 2026",
    grade: "A & B grade",
    deliveryOptions: ["Farm pickup", "Nashik delivery"],
    deliveryRadiusKm: 45,
    certifications: ["Residue-tested", "Verified farm"],
    status: "active",
    viewCount: 1284,
    saveCount: 46,
    enquiryCount: 12,
    createdLabel: "Updated today",
    imageVariant: "tomato-crates",
    seller: getProfile("meera"),
    reviewSummary: { average: 4.8, count: 12 },
  },
  {
    id: "premium-table-grapes",
    sellerId: "suresh",
    title: "Export-grade Thompson grapes",
    crop: "Grapes",
    variety: "Thompson Seedless",
    description:
      "Uniform table grapes grown with documented residue-safe practices. Pre-cooling and packhouse coordination available for volume orders.",
    quantity: 18,
    unit: "tonne",
    minOrder: 500,
    price: 92,
    priceUnit: "kg",
    harvestStart: "10 Feb",
    harvestEnd: "20 Mar",
    availableUntil: "20 Mar 2027",
    grade: "Export grade",
    deliveryOptions: ["Farm pickup", "Packhouse delivery"],
    deliveryRadiusKm: 80,
    certifications: ["Residue-tested", "GlobalG.A.P. in progress"],
    status: "active",
    viewCount: 2189,
    saveCount: 83,
    enquiryCount: 19,
    createdLabel: "Updated 2 days ago",
    imageVariant: "grape-vines",
    seller: getProfile("suresh"),
    reviewSummary: { average: 4.9, count: 19 },
  },
  {
    id: "lasalgaon-red-onions",
    sellerId: "meera",
    title: "Storage-ready red onions",
    crop: "Onion",
    variety: "N-53",
    description:
      "Well-cured red onions graded for shelf life. Suitable for wholesalers, caterers and regular retail supply.",
    quantity: 11,
    unit: "tonne",
    minOrder: 250,
    price: 24,
    priceUnit: "kg",
    harvestStart: "Available now",
    harvestEnd: "15 Sep",
    availableUntil: "15 Sep 2026",
    grade: "45–60 mm",
    deliveryOptions: ["Farm pickup", "Transport arranged"],
    deliveryRadiusKm: 120,
    certifications: ["Verified farm"],
    status: "active",
    viewCount: 846,
    saveCount: 31,
    enquiryCount: 8,
    createdLabel: "Updated yesterday",
    imageVariant: "onion-sacks",
    seller: getProfile("meera"),
    reviewSummary: { average: 4.8, count: 12 },
  },
  {
    id: "pune-okra-baskets",
    sellerId: "ramesh",
    title: "Tender okra for restaurants",
    crop: "Okra",
    variety: "Arka Anamika",
    description:
      "Tender okra picked before sunrise and available in reusable crates. Ideal for restaurants and premium vegetable stores needing consistent sizing.",
    quantity: 900,
    unit: "kg",
    minOrder: 25,
    price: 42,
    priceUnit: "kg",
    harvestStart: "Daily harvest",
    harvestEnd: "30 Sep",
    availableUntil: "30 Sep 2026",
    grade: "Premium",
    deliveryOptions: ["Farm pickup", "Pune delivery"],
    deliveryRadiusKm: 35,
    certifications: ["Verified farm"],
    status: "active",
    viewCount: 612,
    saveCount: 24,
    enquiryCount: 7,
    createdLabel: "Updated 4 hours ago",
    imageVariant: "okra-basket",
    seller: getProfile("ramesh"),
    reviewSummary: { average: 4.6, count: 8 },
  },
  {
    id: "processing-tomatoes",
    sellerId: "ramesh",
    title: "Processing tomatoes — bulk lot",
    crop: "Tomato",
    variety: "Abhinav",
    description:
      "Machine-sortable processing tomatoes with reliable weekly volume. Open to direct contracts with sauce makers and institutional kitchens.",
    quantity: 24,
    unit: "tonne",
    minOrder: 1,
    price: 19,
    priceUnit: "kg",
    harvestStart: "8 Aug",
    harvestEnd: "5 Sep",
    availableUntil: "5 Sep 2026",
    grade: "Processing grade",
    deliveryOptions: ["Farm pickup", "Transport arranged"],
    deliveryRadiusKm: 150,
    certifications: ["Verified farm"],
    status: "active",
    viewCount: 1049,
    saveCount: 39,
    enquiryCount: 14,
    createdLabel: "Updated yesterday",
    imageVariant: "tomato-crates",
    seller: getProfile("ramesh"),
    reviewSummary: { average: 4.6, count: 8 },
  },
  {
    id: "fpo-onion-aggregation",
    sellerId: "vikram",
    title: "FPO aggregated onion supply",
    crop: "Onion",
    variety: "Bhima Shakti",
    description:
      "Aggregated, lot-traceable onions from 22 member farms. Grading, bagging and scheduled dispatch available for institutional buyers.",
    quantity: 74,
    unit: "tonne",
    minOrder: 2,
    price: 26,
    priceUnit: "kg",
    harvestStart: "Available now",
    harvestEnd: "31 Oct",
    availableUntil: "31 Oct 2026",
    grade: "Assorted commercial grades",
    deliveryOptions: ["Collection centre", "Transport arranged"],
    deliveryRadiusKm: 200,
    certifications: ["FPO aggregated", "Lot traceable"],
    status: "active",
    viewCount: 1672,
    saveCount: 55,
    enquiryCount: 21,
    createdLabel: "Updated 3 days ago",
    imageVariant: "onion-sacks",
    seller: getProfile("vikram"),
    reviewSummary: { average: 4.7, count: 15 },
  },
];

export const marketReviews: MarketReview[] = [
  {
    id: "review-1",
    enquiryId: "lead-4",
    listingId: "lasalgaon-red-onions",
    sellerId: "meera",
    rating: 5,
    body: "The onions were well graded, packed carefully and ready exactly when promised. We have already arranged our next monthly collection.",
    createdLabel: "18 Jul",
    listingTitle: "Storage-ready red onions",
  },
  {
    id: "review-2",
    enquiryId: "lead-demo-grapes",
    listingId: "premium-table-grapes",
    sellerId: "suresh",
    rating: 5,
    body: "Clear communication and excellent packing. The trial lot matched the grade described in the listing.",
    createdLabel: "9 Jul",
    listingTitle: "Export-grade Thompson grapes",
  },
  {
    id: "review-3",
    enquiryId: "lead-demo-fpo",
    listingId: "fpo-onion-aggregation",
    sellerId: "vikram",
    rating: 4,
    body: "Reliable bulk quantity and useful lot records. Dispatch coordination was straightforward.",
    createdLabel: "2 Jul",
    listingTitle: "FPO aggregated onion supply",
  },
];

export const marketEnquiries: MarketEnquiry[] = [
  {
    id: "lead-1",
    listingId: "nashik-roma-tomatoes",
    buyerName: "Asha Menon",
    businessName: "Green Basket Stores",
    email: "asha@example.com",
    phone: "+91 98765 41021",
    location: "Nashik, Maharashtra",
    quantityNeeded: "300 kg every week",
    needBy: "5 Aug 2026",
    message:
      "We run three neighbourhood stores and need consistent size and colour. Can you share a sample crate and your weekly dispatch days?",
    status: "new",
    createdLabel: "34 min ago",
    listingTitle: "Fresh Roma tomatoes — weekly harvest",
  },
  {
    id: "lead-2",
    listingId: "lasalgaon-red-onions",
    buyerName: "Rahul Bhat",
    businessName: "Satvik Kitchens",
    email: "rahul@example.com",
    phone: "+91 98220 14567",
    location: "Pune, Maharashtra",
    quantityNeeded: "500 kg",
    needBy: "8 Aug 2026",
    message:
      "We are comparing direct weekly supply for our central kitchen. Please confirm bag size and delivery cost to Pune.",
    status: "contacted",
    createdLabel: "Yesterday",
    listingTitle: "Storage-ready red onions",
  },
  {
    id: "lead-3",
    listingId: "nashik-roma-tomatoes",
    buyerName: "Fatima Shaikh",
    businessName: "Community Harvest Co-op",
    email: "fatima@example.com",
    phone: "+91 98901 77412",
    location: "Mumbai, Maharashtra",
    quantityNeeded: "150 kg trial order",
    needBy: "12 Aug 2026",
    message:
      "Our member families are looking for residue-tested produce with the farmer story included. Interested in a trial order.",
    status: "qualified",
    createdLabel: "2 days ago",
    listingTitle: "Fresh Roma tomatoes — weekly harvest",
  },
  {
    id: "lead-4",
    listingId: "lasalgaon-red-onions",
    buyerName: "Nitin More",
    businessName: "More Fresh Mart",
    email: "nitin@example.com",
    phone: "+91 97644 29220",
    location: "Nashik, Maharashtra",
    quantityNeeded: "1 tonne per month",
    needBy: "Ongoing",
    message:
      "Looking for a stable monthly supplier. We can collect from the farm if loading support is available.",
    status: "won",
    buyerId: "anjali",
    conversationId: "conversation-anjali",
    createdLabel: "12 Jul",
    listingTitle: "Storage-ready red onions",
    seller: getProfile("meera"),
    review: marketReviews[0],
  },
];

export function getProduceListing(id: string) {
  return produceListings.find((listing) => listing.id === id) ?? null;
}

export function getStoreListings(handle: string) {
  return produceListings.filter(
    (listing) => listing.seller?.handle === handle && listing.status === "active",
  );
}
